### ISSUE TITLE
errors in estimate_tuning

### ISSUE THREAD

**Issue by bmcfee** [bmcfee/librosa#151]
The tuning estimator fails 52 / 72 unit tests on a simple harmonic input.

Tuning estimation from frequency measurement input (ie, `librosa.core.pitch.pitch_tuning`) works, so these errors are due to `piptrack`.

```
test_core.test_estimate_tuning(427.4740541075866, 0.01, 12, -0.5) ... ok
test_core.test_estimate_tuning(430.57170731858804, 0.01, 12, -0.375) ... FAIL
test_core.test_estimate_tuning(433.6918074016825, 0.01, 12, -0.25) ... FAIL
test_core.test_estimate_tuning(440.0, 0.01, 12, 0.0) ... FAIL
test_core.test_estimate_tuning(446.39994737251044, 0.01, 12, 0.25) ... ok
test_core.test_estimate_tuning(449.6347454078113, 0.01, 12, 0.375) ... ok
test_core.test_estimate_tuning(1016.7103732476002, 0.01, 12, -0.5) ... ok
test_core.test_estimate_tuning(1024.077875724268, 0.01, 12, -0.375) ... ok
test_core.test_estimate_tuning(1031.4987661609414, 0.01, 12, -0.25) ... FAIL
test_core.test_estimate_tuning(1046.5022612023945, 0.01, 12, 0.0) ... ok
test_core.test_estimate_tuning(1061.7239871044592, 0.01, 12, 0.25) ... FAIL
test_core.test_estimate_tuning(1069.4176767828126, 0.01, 12, 0.375) ... ok
test_core.test_estimate_tuning(4066.8414929904015, 0.01, 12, -0.5) ... ok
test_core.test_estimate_tuning(4096.311502897072, 0.01, 12, -0.375) ... FAIL
test_core.test_estimate_tuning(4125.995064643765, 0.01, 12, -0.25) ... FAIL
test_core.test_estimate_tuning(4186.009044809578, 0.01, 12, 0.0) ... FAIL
test_core.test_estimate_tuning(4246.895948417838, 0.01, 12, 0.25) ... FAIL
test_core.test_estimate_tuning(4277.67070713125, 0.01, 12, 0.375) ... FAIL
test_core.test_estimate_tuning(427.4740541075866, 0.001, 12, -0.5) ... FAIL
test_core.test_estimate_tuning(430.57170731858804, 0.001, 12, -0.375) ... FAIL
test_core.test_estimate_tuning(433.6918074016825, 0.001, 12, -0.25) ... FAIL
test_core.test_estimate_tuning(440.0, 0.001, 12, 0.0) ... FAIL
test_core.test_estimate_tuning(446.39994737251044, 0.001, 12, 0.25) ... FAIL
test_core.test_estimate_tuning(449.6347454078113, 0.001, 12, 0.375) ... FAIL
test_core.test_estimate_tuning(1016.7103732476002, 0.001, 12, -0.5) ... ok
test_core.test_estimate_tuning(1024.077875724268, 0.001, 12, -0.375) ... FAIL
test_core.test_estimate_tuning(1031.4987661609414, 0.001, 12, -0.25) ... FAIL
test_core.test_estimate_tuning(1046.5022612023945, 0.001, 12, 0.0) ... FAIL
test_core.test_estimate_tuning(1061.7239871044592, 0.001, 12, 0.25) ... FAIL
test_core.test_estimate_tuning(1069.4176767828126, 0.001, 12, 0.375) ... FAIL
test_core.test_estimate_tuning(4066.8414929904015, 0.001, 12, -0.5) ... ok
test_core.test_estimate_tuning(4096.311502897072, 0.001, 12, -0.375) ... FAIL
test_core.test_estimate_tuning(4125.995064643765, 0.001, 12, -0.25) ... FAIL
test_core.test_estimate_tuning(4186.009044809578, 0.001, 12, 0.0) ... FAIL
test_core.test_estimate_tuning(4246.895948417838, 0.001, 12, 0.25) ... FAIL
test_core.test_estimate_tuning(4277.67070713125, 0.001, 12, 0.375) ... FAIL
test_core.test_estimate_tuning(427.4740541075866, 0.01, 12, -0.5) ... FAIL
test_core.test_estimate_tuning(430.57170731858804, 0.01, 12, -0.375) ... ok
test_core.test_estimate_tuning(433.6918074016825, 0.01, 12, -0.25) ... ok
test_core.test_estimate_tuning(440.0, 0.01, 12, 0.0) ... FAIL
test_core.test_estimate_tuning(446.39994737251044, 0.01, 12, 0.25) ... ok
test_core.test_estimate_tuning(449.6347454078113, 0.01, 12, 0.375) ... ok
test_core.test_estimate_tuning(1016.7103732476002, 0.01, 12, -0.5) ... ok
test_core.test_estimate_tuning(1024.077875724268, 0.01, 12, -0.375) ... ok
test_core.test_estimate_tuning(1031.4987661609414, 0.01, 12, -0.25) ... ok
test_core.test_estimate_tuning(1046.5022612023945, 0.01, 12, 0.0) ... FAIL
test_core.test_estimate_tuning(1061.7239871044592, 0.01, 12, 0.25) ... FAIL
test_core.test_estimate_tuning(1069.4176767828126, 0.01, 12, 0.375) ... ok
test_core.test_estimate_tuning(4066.8414929904015, 0.01, 12, -0.5) ... ok
test_core.test_estimate_tuning(4096.311502897072, 0.01, 12, -0.375) ... FAIL
test_core.test_estimate_tuning(4125.995064643765, 0.01, 12, -0.25) ... FAIL
test_core.test_estimate_tuning(4186.009044809578, 0.01, 12, 0.0) ... FAIL
test_core.test_estimate_tuning(4246.895948417838, 0.01, 12, 0.25) ... FAIL
test_core.test_estimate_tuning(4277.67070713125, 0.01, 12, 0.375) ... FAIL
test_core.test_estimate_tuning(427.4740541075866, 0.001, 12, -0.5) ... FAIL
test_core.test_estimate_tuning(430.57170731858804, 0.001, 12, -0.375) ... FAIL
test_core.test_estimate_tuning(433.6918074016825, 0.001, 12, -0.25) ... FAIL
test_core.test_estimate_tuning(440.0, 0.001, 12, 0.0) ... FAIL
test_core.test_estimate_tuning(446.39994737251044, 0.001, 12, 0.25) ... FAIL
test_core.test_estimate_tuning(449.6347454078113, 0.001, 12, 0.375) ... FAIL
test_core.test_estimate_tuning(1016.7103732476002, 0.001, 12, -0.5) ... FAIL
test_core.test_estimate_tuning(1024.077875724268, 0.001, 12, -0.375) ... FAIL
test_core.test_estimate_tuning(1031.4987661609414, 0.001, 12, -0.25) ... FAIL
test_core.test_estimate_tuning(1046.5022612023945, 0.001, 12, 0.0) ... FAIL
test_core.test_estimate_tuning(1061.7239871044592, 0.001, 12, 0.25) ... FAIL
test_core.test_estimate_tuning(1069.4176767828126, 0.001, 12, 0.375) ... FAIL
test_core.test_estimate_tuning(4066.8414929904015, 0.001, 12, -0.5) ... ok
test_core.test_estimate_tuning(4096.311502897072, 0.001, 12, -0.375) ... FAIL
test_core.test_estimate_tuning(4125.995064643765, 0.001, 12, -0.25) ... FAIL
test_core.test_estimate_tuning(4186.009044809578, 0.001, 12, 0.0) ... FAIL
test_core.test_estimate_tuning(4246.895948417838, 0.001, 12, 0.25) ... FAIL
test_core.test_estimate_tuning(4277.67070713125, 0.001, 12, 0.375) ... FAIL
```

**Comment by craffel** [comment]
Where is this test and by how much is it failing?

**Comment by bmcfee** [comment]
> Where is this test and by how much is it failing?

Check the develop branch, test_core.test_estimate_tuning.

**Comment by craffel** [comment]
Is it a problem with the thresholding you're doing? (https://github.com/bmcfee/librosa/blob/develop/librosa/core/pitch.py#L67)

```Python
In [32]: import numpy as np

In [33]: import librosa

In [34]: sr = 11025

In [35]: duration = 5.0

In [36]: t = np.linspace(0, duration, duration*sr)

In [37]: y = np.sin(2 * np.pi * target_hz * t)

In [38]: pitch, mag = librosa.piptrack(y=y, sr=sr)

In [39]: pitch_mask = pitch > 0

In [40]: pitch_mask.any()
Out[40]: True

In [41]: threshold = np.median(mag[pitch_mask])

In [42]: pitch[(mag > threshold) & pitch_mask]
Out[42]: array([], dtype=float32)
```

**Comment by bmcfee** [comment]
Intriguing point!  That should really be a `>=`.

**Comment by bmcfee** [comment]
... that said, changing to a >=, it still fails in the same cases.

**Comment by craffel** [comment]
After this change, 
```Python
pitch[(mag > threshold) & pitch_mask]
```
yields
```Python
array([ 427.28393555,  430.57192993,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60058594,  430.60058594,  430.60058594,  430.60058594,
        430.60025024,  430.1567688 ,  433.97189331], dtype=float32)
```

Is this not OK?  The target_hz is 430.57170731858804.  Is it worse in other cases?

**Comment by bmcfee** [comment]
You  mean `pitch[(mag >= threshold) & pitch_mask]`?

Yes, in that case, it works, and estimates the tuning within 0.5 cents, and the test passes.

But it still fails in the majority of remaining cases:

```
test_core.test_estimate_tuning(427.4740541075866, 0.01, 12, -0.5) ... ok
test_core.test_estimate_tuning(430.57170731858804, 0.01, 12, -0.375) ... ok
test_core.test_estimate_tuning(433.6918074016825, 0.01, 12, -0.25) ... FAIL
test_core.test_estimate_tuning(440.0, 0.01, 12, 0.0) ... FAIL
```

and so on.

**Comment by craffel** [comment]
> You mean pitch[(mag >= threshold) & pitch_mask]?

Haha no, I changed 
```
pitch_mask = pitch >= 0
```

> But it still fails in the majority of remaining cases:

I don't think it's because of piptrack, unless these estimates are not good enough. 

```Python
target_hz = 433.6918074016825
y = np.sin(2 * np.pi * target_hz * t)
pitch, mag = librosa.piptrack(y=y, sr=sr)
pitch_mask = pitch >= 0
threshold = np.median(mag[pitch_mask])
pitch[(mag > threshold) & pitch_mask]
```
(`t`, `sr`, etc all defined as above) yields
```Python
array([ 430.22036743,  433.70071411,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61798096,  433.61798096,  433.61798096,  433.61798096,
        433.61843872,  433.30184937,  436.79724121], dtype=float32)
```
and  `target_hz = 440` yields
```Python
array([ 436.36004639,  439.99731445,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96273804,  439.96273804,  439.96273804,  439.96273804,
        439.96298218,  440.02789307,  443.61868286], dtype=float32)
```

**Comment by bmcfee** [comment]
> pitch_mask = pitch >= 0

Not sure this change makes sense?  We can't use ``pitch == 0`` to estimate tuning, right?

Meanwhile, I relaxed the tests a bit and we're down to 4 failures as of 381d7e2e2c2adc01fda8d50f16f9c4d6e9a3814c.  This includes the following changes:

- Removed tests at 11025Hz
- Removed tests for ``resolution=1e-3``
- Changed the test logic from
```
assert np.abs(tuning_est - tuning_ref) <= resolution
```
to
```
deviation = np.around(np.abs(tuning_est - tuning_ref), int(-np.log10(resolution)))
assert deviation <= resolution
```
This avoids some floating point precision errors.

The remaining errors are "sensible" in that they're off by a few cents, and mainly occur at lower notes.

```
======================================================================
FAIL: test_core.test_estimate_tuning(427.4740541075866, 0.01, 12, -0.5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/bmcfee/git/librosa/tests/test_core.py", line 360, in __test
    assert deviation <= resolution
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
target_hz=427.474
tuning=-0.500, estimated=-0.480
resolution=1.00e-02

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: test_core.test_estimate_tuning(433.6918074016825, 0.01, 12, -0.25)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/bmcfee/git/librosa/tests/test_core.py", line 360, in __test
    assert deviation <= resolution
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
target_hz=433.692
tuning=-0.250, estimated=-0.280
resolution=1.00e-02

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: test_core.test_estimate_tuning(449.6347454078113, 0.01, 12, 0.375)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/bmcfee/git/librosa/tests/test_core.py", line 360, in __test
    assert deviation <= resolution
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
target_hz=449.635
tuning=0.375, estimated=0.390
resolution=1.00e-02

--------------------- >> end captured stdout << ----------------------

======================================================================
FAIL: test_core.test_estimate_tuning(1069.4176767828126, 0.01, 12, 0.375)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/bmcfee/git/librosa/tests/test_core.py", line 360, in __test
    assert deviation <= resolution
AssertionError: 
-------------------- >> begin captured stdout << ---------------------
target_hz=1069.418
tuning=0.375, estimated=0.360
resolution=1.00e-02

--------------------- >> end captured stdout << ----------------------
```
