### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by srviest** [bmcfee/librosa#290]
librosa worked fine until recently, 
when I import librosa:
╰─$ python -c 'import librosa'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "build/bdist.macosx-10.9-x86_64/egg/librosa/__init__.py", line 15, in <module>
  File "build/bdist.macosx-10.9-x86_64/egg/librosa/core/__init__.py", line 89, in <module>
  File "build/bdist.macosx-10.9-x86_64/egg/librosa/core/audio.py", line 34, in <module>
  File "/usr/local/lib/python2.7/site-packages/scikits.samplerate-0.3.3-py2.7-macosx-10.9-x86_64.egg/scikits/samplerate/__init__.py", line 6, in <module>
    from _samplerate import resample, available_convertors, src_version_str, \
  File "numpy.pxd", line 43, in scikits.samplerate._samplerate (/private/tmp/easy_install-S5qsl5/scikits.samplerate-0.3.3/scikits/samplerate/_samplerate.c:3807)
ValueError: numpy.dtype does not appear to be the correct type object

I've referred to the #277 and with scikits.samplerate and libsamplerate installed.
Does anybody know what's going on? 
Thanks a lot.

**Comment by bmcfee** [comment]
This is a problem with scikits.samplerate, not librosa.

The issue, I believe, is that the binary api for numpy changed at 1.10.  scikits.samplerate still works, but you need to rebuild the module from source (not from pypi).

As a side note, I keep a fork of scikits.samplerate for python3 compatibility, which is what gets used in our test suite.  You can install it by saying:
```
pip install git+https://github.com/bmcfee/samplerate.git
```

**Comment by bmcfee** [comment]
[tagging @rabitt who has also noted this issue]

**Comment by srviest** [comment]
To @bmcfee, it works now, Thank you!
